### ISSUE TITLE
Tables overflow if content is too wide

### ISSUE THREAD

**Issue by matthew-morris-cessda** [cessda/cessda.documentation.theme#10]
See https://elsst.cessda.eu/structure/bibliography for an example.

**Comment by matthew-morris-cessda** [comment]
This only affects links within tables. This happens regardless of the CSS styling that's supposed to prevent this:

```css
a {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
```
